---
# file: main.yml

- name: Ensure cowrie ownership
  file:
    path: "{{ cowrie_location }}"
    owner: "{{ cowrie_user }}"
    group: "{{ cowrie_user }}"

- name: Ensure prereq Python packages in Virtual Environment
  become: true
  become_user: "{{ cowrie_user }}"
  pip:
    name: ['pip>9', 'setuptools>18.5']
    virtualenv: "{{ cowrie_venv }}"
    virtualenv_python: "python2"
    state: present

- name: Ensure requirements.txt Python packages in Virtual Environment
  become: true
  become_user: "{{ cowrie_user }}"
  pip:
    requirements: "{{ cowrie_location }}/requirements.txt"
    virtualenv: "{{ cowrie_venv }}"
    state: present

- name: Install optional Python packages in Virtual Environment
  become: true
  become_user: "{{ cowrie_user }}"
  pip:
    requirements: "{{ cowrie_location }}/requirements-output.txt"
    virtualenv: "{{ cowrie_venv }}"
    state: present

- name: Install geo lite 2
  become: true
  become_user: "{{ cowrie_user }}"
  pip:
    name: python-geoip-geolite2
    virtualenv: "{{ cowrie_venv }}"
    state: present

- name: Copy config file
  become: true
  become_user: "{{ cowrie_user }}"
  template:
    src: ./cowrie.cfg.j2
    dest: "{{ cowrie_location }}/etc/cowrie.cfg"

- name: Copy user db
  become: true
  become_user: "{{ cowrie_user }}"
  copy:
    src: ./userdb.txt
    dest: "{{ cowrie_location }}/etc/userdb.txt"

- name: Copy service file
  template:
    src: ./cowrie.service.j2
    dest: /etc/systemd/system/cowrie.service

- name: Enable and reload cowrie service
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: cowrie

- name: Ensure script folder existence
  file:
    path: "{{ cowrie_scripts_location }}"
    owner: "{{ cowrie_user }}"
    group: "{{ cowrie_user }}"
    state: directory

- name: Ensure dataset folder existence
  file:
    path: "{{ cowrie_dataset_location }}"
    owner: "{{ cowrie_user }}"
    group: "{{ cowrie_user }}"
    state: directory

- name: Copy extract auth entries file
  template:
    src: ./extract_auth_entries.py
    dest: "{{ cowrie_scripts_location }}/extract_auth_entries.py"
    owner: "{{ cowrie_user }}"
    group: "{{ cowrie_user }}"
    mode: 0770
    
- name: Copy extract session entries file
  template:
    src: ./extract_session_entries.py
    dest: "{{ cowrie_scripts_location }}/extract_session_entries.py"
    owner: "{{ cowrie_user }}"
    group: "{{ cowrie_user }}"
    mode: 0770
    
