---
# file: main.yml

- name: Redirect port 22 to 2222
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 22
    jump: REDIRECT
    to_ports: 2222
    comment: Redirect ssh traffic to port 2222

